Repository buildtesters/lmodule, pull requests merged in 2022-10, with the labels that each got.

#23 make sure all commands run in login mode
  lmod/module.py
  tests/test_modules.py
Labels: size/M

#26 add dependabot for auto-update versions for github actions and pypi
  .github/dependabot.yml
Labels: size/S

#24 update documentation on modules page
  docs/module.rst
Labels: size/M

#25 update codecov settings for commenting on PRs
  .codecov.yml
  .coveragerc
  .github/workflows/regression.yml
Labels: size/S

#22 Update urlchecker.yml
  .github/workflows/urlchecker.yml
Labels: size/XS

#31 update black settings in regression test, pre-commit for black and applying black to source code
  .github/workflows/black.yml
  .pre-commit-config.yaml
  lmod/module.py
Labels: size/XS

#32 update badges
  README.rst
  docs/index.rst
Labels: size/S

#33 fix broken link for EasyBuild User Meeting conference talk
  README.rst
Labels: size/XS

#34 add example modulefiles to be used in regression test to test spider class
  README.rst
  docs/conf.py
  tests/modules/core/gcc/.modulerc.lua
  tests/modules/core/gcc/9.3.0.lua
  tests/modules/gcc/openmpi/.version
  tests/modules/gcc/openmpi/3.0.lua
  tests/modules/gcc/openmpi/3.1.lua
  tests/test_modules.py
  tests/test_spider.py
Labels: size/M

#35 lmodule version 0.3.0
  .gitignore
  CHANGELOG.rst
  lmod/__init__.py
Labels: size/S
